// Mobile navigation is shared by both language versions.
const et=document.documentElement.lang==='et';
const labels=et?{home:'Avaleht',courses:'Kursused',atlas:'Atlas',practice:'Harjutused',more:'Veel',menu:'Kõik jaotised',close:'Sulge',labs:'Labor',glossary:'Sõnastik',projects:'Uurimistööd',progress:'Minu edenemine',about:'Õppekava ja allikad',back:'Tagasi kursuse juurde',map:'Kaarti saad sõrmega külgsuunas liigutada. Väikeriikide leidmiseks vali Euroopa suurendus.'}:{home:'Главная',courses:'Курсы',atlas:'Атлас',practice:'Практика',more:'Ещё',menu:'Все разделы',close:'Закрыть',labs:'Лаборатория',glossary:'Словарь',projects:'Исследования',progress:'Мой прогресс',about:'О программе и источниках',back:'К программе курса',map:'Сдвигай карту пальцем в сторону. Для небольших стран выбери увеличение Европы.'};
const paths={home:'M3 10 12 3l9 7v10H3zM9 20v-7h6v7',courses:'M4 4h16v16H4zM8 8h8M8 12h8M8 16h5',atlas:'M3 12h18M12 3c6 6 6 12 0 18M12 3c-6 6-6 12 0 18',practice:'m9 4 2 5 5 2-5 2-2 5-2-5-5-2 5-2zM19 3v4M17 5h4',more:'M4 6h16M4 12h16M4 18h16',labs:'M9 3h6M10 3v7l-6 10h16l-6-10V3M7 15h10',glossary:'M4 5h7v15H4zM13 5h7v15h-7z',projects:'M4 5h16v15H4zM8 3v4M16 3v4M8 11h8M8 15h5',progress:'M4 20V10M10 20V6M16 20V3M3 20h18',about:'M12 11v6M12 7h.01'};
const icon=id=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${['atlas','about'].includes(id)?'<circle cx="12" cy="12" r="9"/>':''}<path d="${paths[id]}"/></svg>`;
const brand=document.createElement('a');brand.className='mobile-brand';brand.href='#home';brand.innerHTML='<img src="./logo.svg" width="30" height="30" alt="">GEO';brand.setAttribute('aria-label',labels.home);document.querySelector('.topbar').prepend(brand);
const nav=document.createElement('nav');nav.className='mobile-nav';nav.setAttribute('aria-label',et?'Põhinavigatsioon':'Основная навигация');nav.innerHTML=['home','courses','atlas','practice'].map(id=>`<a href="#${id}" data-mobile-route="${id}">${icon(id)}<span>${labels[id]}</span></a>`).join('')+`<button type="button" id="mobile-more" aria-haspopup="dialog" aria-controls="mobile-menu">${icon('more')}<span>${labels.more}</span></button>`;document.body.append(nav);
const dialog=document.createElement('dialog');dialog.id='mobile-menu';dialog.className='mobile-menu';dialog.setAttribute('aria-labelledby','mobile-menu-title');dialog.innerHTML=`<div class="sheet-handle" aria-hidden="true"></div><div class="sheet-heading"><h2 id="mobile-menu-title">${labels.menu}</h2><button type="button" class="sheet-close" aria-label="${labels.close}">×</button></div><div class="sheet-links">${['labs','glossary','projects','progress','about'].map(id=>`<a href="#${id}">${icon(id)}<span>${labels[id]}</span><b aria-hidden="true">→</b></a>`).join('')}</div>`;document.body.append(dialog);
const more=document.getElementById('mobile-more');more.addEventListener('click',()=>{dialog.showModal();document.body.classList.add('sheet-open');});function closeMenu(){if(dialog.open)dialog.close();document.body.classList.remove('sheet-open');}dialog.querySelector('.sheet-close').addEventListener('click',closeMenu);dialog.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));dialog.addEventListener('close',()=>document.body.classList.remove('sheet-open'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientY<r.top||e.clientY>r.bottom||e.clientX<r.left||e.clientX>r.right)closeMenu();}});
function update(){const [route,id]=(location.hash.slice(1)||'home').split('/'),active=['course','lesson'].includes(route)?'courses':['quiz','flash'].includes(route)?'practice':route;nav.querySelectorAll('[data-mobile-route]').forEach(a=>{const selected=a.dataset.mobileRoute===active;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});more.classList.toggle('active',!['home','courses','atlas','practice','search'].includes(active));document.body.dataset.route=route;document.querySelector('.mobile-back')?.remove();if(route==='lesson'){const lesson=document.querySelector('.lesson-article'),match=document.querySelector('.reading-grid a[href^="#course/"]');if(lesson&&match){const back=document.createElement('a');back.className='mobile-back';back.href=match.getAttribute('href');back.textContent='← '+labels.back;document.querySelector('main').prepend(back);}}if(route==='atlas'&&!document.querySelector('.mobile-map-hint')){const hint=document.createElement('p');hint.className='mobile-map-hint';hint.textContent=labels.map;document.querySelector('.map-shell')?.before(hint);}closeMenu();}
window.addEventListener('hashchange',update);document.addEventListener('geo:render',update);update();
function centerMap(){const shell=document.querySelector('.map-shell');if(shell&&matchMedia('(max-width:760px)').matches)shell.scrollLeft=(shell.scrollWidth-shell.clientWidth)/2;}
document.addEventListener('geo:render',centerMap);window.addEventListener('hashchange',centerMap);centerMap();
